#!/bin/bash
# convert='/c/users/pih/desktop/portableprograms/ImageMagick/convert.exe'
# gs='/c/users/pih/desktop/portableprograms/Ghostscript/bin/gswin64.exe'

# build
pdflatex main

# bibliography
biber main

# build and rebuild
pdflatex main && pdflatex main

# compress
# convert -density 100x100 -quality 60 main.pdf main_comp.pdf
